"""Add User.user_timezone

Revision ID: d63960a658a0
Revises: b9814dec40b8
Create Date: 2024-07-12 19:33:57.662418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63960a658a0'
down_revision = 'b9814dec40b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_timezone')
    # ### end Alembic commands ###
