"""Add users.verification_token

Revision ID: fbe44eb66d42
Revises: b9814dec40b8
Create Date: 2024-07-03 17:13:20.357593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe44eb66d42'
down_revision = 'b9814dec40b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['verification_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
